program bom_exe
!
! Create a Fortran source file starting with a utf-8 BOM to see if your
! compiler will compile it or fail because a character is not in the
! Fortran character set outside of a comment or literal string.
!
! When the first character of a file the BOM character indicates the file
! is UTF-8 encoded to some applications, although it is not universally
! required.
!
! Does your compiler compile the output file generated by this program?
!
! The Unicode value for the Byte Order Mark (BOM) character is
! U+FEFF. While it was originally used as a "Zero Width No-Break Space,"
! its modern purpose is solely to act as a BOM, indicating the file is
! Unicode encoded and, in the case of UTF-16 and UTF-32, its byte order
! (endianness). The BOM is often presented at the beginning of a file,
! though its use in UTF-8 files is primarily to signal the encoding, not
! to address byte order issues (which does not apply to UTF-8 encoding).
!
! if on a ULS (Unix-like system) the file(1) command should produce
!
!     bom_start >>xx.f90
!     file xx.f90
!     xx.f90: Unicode text, UTF-8 (with BOM) text
!
use iso_fortran_env, only : stdout => output_unit
use M_unicode, only : unicode_type, assignment(=), unicode
implicit none
type(unicode_type) :: UT_bom
   UT_bom=65279        ! the codepoint value for the BOM character
   UT_bom=int(z'FEFF') ! or equivalently 
   UT_bom=unicode%bom  ! alternatively use constant from module

   ! place BOM character at beginning of output
   write(stdout,'(a)',advance='no')UT_bom%character()
   ! add a minimal Fortran program to make a test program source
   write(stdout,'(a)') &

    'program testit ! Unicode BOM encoded to utf-8 bytes by Fortran' ,&
    '   write(*,*)"This source file starts with BOM character(z""FEFF"")!"',&
    'end program testit'

end program bom_exe
