name = "M_unicode"
version = "1.3.0"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2025,2026 John S. Urban"
description = "UTF-8 encoded string processing"
categories = ["strings"]
keywords = ["fortran", "strings","Unicode","UTF-8"]
homepage = "https://github.com/urbanjost/M_unicode.git"

[install]
   library = true

[[executable]]
   name="utf8_to_backslash"
   source-dir="app"
   main="utf8_to_backslash.f90"
