name = "M_unicode"
version = "2.0.0"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2025,2026 John S. Urban"
description = "UTF-8 encoded string processing"
categories = ["strings"]
keywords = ["fortran", "strings","Unicode","UTF-8", "utf8", "internationalization", "i18n" ]
homepage = "https://github.com/urbanjost/M_unicode.git"

[install]
   library = true

[[executable]]
   name="utf8_to_backslash"
   source-dir="app"
   main="utf8_to_backslash.f90"

[[executable]]
   name="backslash_to_utf8"
   source-dir="app"
   main="backslash_to_utf8.f90"
